name: main-pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      app_version:
        description: 'The is the release tag that doubles as the image tag and application version'
        required: true
        default: ''  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: build application
      run: |
        echo "Building the Application"

  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: test application
      run: |
        echo "Testing the Application"

  release:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: build and push image to registry
      run: |
        echo "Building and Tagging Image as ${{ github.event.inputs.app_version}}"
        echo "Pushing Image ${{ github.event.inputs.app_version}} to registry"
    
    - name: deploying the application
      run: |
        echo "Deploying Version ${{ github.event.inputs.app_version }}"
    
    - name: release the application
      if: success()
      run: |
        gh release create ${{ github.event.inputs.app_version }} -F ./docs/changelog/CHANGELOG-${{ github.event.inputs.app_version }}.md
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
