# this is liken to the production flow to deploy to production. 
# Add the heroku deploy action to this for automatic deployment
name: Build Node App
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deployer:
        description: 'Deployment Officer'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: build with node versions ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: start continuous integration
      run: npm ci
    - name: start build
      run: npm run build --if-present
    - name: start test
      run: npm test
    - name: deployer
      run: echo "Ran by ${{ github.event.inputs.deployer }}"

  # qualify:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Initialize CodeQL
  #       uses: github/codeql-action/init@v1
  #       with:
  #         languages: javascript
  #     - name: Code Quality
  #       uses: github/codeql-action/analyze@v1    