# this is liken to the production flow to deploy to production. 
# Add the heroku deploy action to this for automatic deployment
name: main-pipeline
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image Tag'
        required: true
        default: ''  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: deployer
      run: |
        echo "Ran by ${{ github.event.inputs.deployer }}"
        echo "Running Version ${{ github.event.inputs.image_tag }}"
    - name: Release the Application
      if: success() && github.event_name == 'workflow_dispatch'
      run: |
        gh release create ${{ github.event.inputs.image_tag }} -F docs/changelog/CHANGELOG-${{ github.event.inputs.image_tag }}.md
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ## once this runs it should trigger an on release workflow or even on release job that then deploys a live application 
